version: 0.0
os: linux
files:
  - source: /site.yml
    destination: /var/www/yml/
hooks:
  BeforeInstall:
    - location: deployment.yml
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: restart.yml
      timeout: 300
      runas: ec2-user
