version: 0.0
os: linux
files:
  - source: /*
    destination: /home/ec2-user/Target
hooks:
  BeforeInstall:
    - location: deploy.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: restart.sh
      timeout: 300
      runas: ec2-user
