version: 0.0
os: linux
files:
  - source: /*
    destination: /home/ec2-user/Target
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: restart.sh
      timeout: 300
      runas: root
