version: 0.0
os: linux
files:
  - source: /sample.war
    destination: /home/ec2-user/Target
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: restart.sh
      timeout: 300
      runas: ec2-user
