version: 0.2

phases:
  pre_build:
    commands:
      - go version

  build:
    commands:
      - go build -o myapp myapp
      - go build -o yourapp yourapp
      - go build -o momapp momapp

artifacts:
  files:
    - 'myapp'
    - 'yourapp'
    - 'momapp'
  discard-paths: yes

cache:
  paths:
    - '/go/pkg/mod'
